spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}/forif_dev
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

