spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul

  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    default-model-expand-depth: 2
    default-models-expand-depth: 2
    path: /api-docs
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  paths-to-match:
    - /**
