spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul

  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate:
        jdbc:
          batch_size: 100

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ${JWT_SECRET}

notification:
  api-key: ${SMS_API_KEY}
  api-secret: ${SMS_API_SECRET}
  pf-id: ${SMS_PF_ID}
  sender-number: ${SMS_SENDER_NUMBER}

app:
  file:
    storage: ${FILE_STORAGE:local}
    local:
      root-path: ${FILE_STORAGE_ROOT:./storage/uploads}
      public-url: ${FILE_PUBLIC_URL:}

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    default-model-expand-depth: 2
    default-models-expand-depth: 2
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  paths-to-match:
    - /**
