spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}/forif_dev
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


logging:
  level:
    org.hibernate.SQL: debug
